//
//  RecipeDetailInteractor.swift
//  MarleySpoon
//
//  Created Gagan Vishal on 2020/01/24.
//  Copyright © 2020 Gagan Vishal. All rights reserved.
//
//  Template generated by Gagan Vishal @gagan5278
//

import UIKit

class RecipeDetailInteractor: RecipeDetailInteractorProtocol {

    weak var presenter: RecipeDetailPresenterProtocol?
}
