//
//  RecipeDetailPresenter.swift
//  MarleySpoon
//
//  Created Gagan Vishal on 2020/01/24.
//  Copyright © 2020 Gagan Vishal. All rights reserved.
//
//  Template generated by Gagan Vishal @gagan5278
//

import UIKit

class RecipeDetailPresenter: RecipeDetailPresenterProtocol {
    
    weak private var view: RecipeDetailViewProtocol?
    var interactor: RecipeDetailInteractorProtocol?
    private let router: RecipeDetailWireframeProtocol
    private let model: RecipeModel
    init(interface: RecipeDetailViewProtocol, interactor: RecipeDetailInteractorProtocol?, router: RecipeDetailWireframeProtocol, model: RecipeModel) {
        self.view = interface
        self.interactor = interactor
        self.router = router
        self.model = model
        
    }
    //MARK:- View loaded
    func viewLoaded() {
        //1.
        view?.didLoadDetail(from: AttributedStringHelper.createAttributedString(from: self.model.title + "\n\n", descriptionString: self.model.description, titleFont: CustomFont.semibold.font(with: 20.0), titleTextColor: UIColor.titleColor, descriptionFont: CustomFont.regular.font(with: 16.0), descriptionTextColor: UIColor.descriptionColor))
        //2.
        loadDetailImage()
    }
    
    //MARK:- Show user alers
    func showAlert(with title: String, message: String, view: RecipeDetailViewProtocol, buttonTitle: String, withCallback callBack: ((UIAlertAction) -> Void)?) {
        self.router.showAlert(with: title, message: message, view: view, buttonTitle: buttonTitle, withCallback: callBack)
    }
    
    private func loadDetailImage() {
        ImageDownloadManager.sharedInsatnce.downloadUserAvtarImage(avatar_url: APIRouter.fullSizeImageFor(url: self.model.photo.url!).urlString) { (imageDownloaded, _, _, _) in
            DispatchQueue.main.async {[weak self] in
                self?.view?.didLoad(image: imageDownloaded)
            }
        }
    }
}
