//
//  RecipeListInteractor.swift
//  MarleySpoon
//
//  Created Gagan Vishal on 2020/01/25.
//  Copyright © 2020 Gagan Vishal. All rights reserved.
//
//  Template generated by Gagan Vishal @gagan5278
//

import UIKit

class RecipeListInteractor: RecipeListInteractorInputProtocol {
    var remoteDataManager: RecipeRemoteDataManagerInputProtocol?
    weak var presenter: RecipeListInteractorOutputProtocol?
    
    //MARK:- Fetch list of recipe from server
    func fetchRecipeListFromServer() {
        self.remoteDataManager?.retrieveRecipeList()
    }
}

extension RecipeListInteractor: RecipeRemoteDataManagerOutputProtocol {
    func onRecieveRecipe(item: [RecipeModel]) {
        presenter?.onRecieveRecipe(items: item)
    }

    func onRecieve(error: APIError) {
        presenter?.onRecieveServer(error: error)
    }
}
