//
//  RecipeDetailProtocols.swift
//  MarleySpoon
//
//  Created Gagan Vishal on 2020/01/24.
//  Copyright © 2020 Gagan Vishal. All rights reserved.
//
//  Template generated by Gagan Vishal @gagan5278
//

import Foundation
import UIKit
//MARK: Wireframe -
protocol RecipeDetailWireframeProtocol: class {
    func showAlert(with title: String, message: String, view: RecipeDetailViewProtocol, buttonTitle: String, withCallback callBack: ((UIAlertAction) -> Void)?)
}
//MARK: Presenter -
protocol RecipeDetailPresenterProtocol: class {
    //1. call when view is loaded
   func viewLoaded()
   //show user message
   func showAlert(with title: String, message: String, view: RecipeDetailViewProtocol, buttonTitle: String, withCallback callBack: ((UIAlertAction) -> Void)?)
}

//MARK: Interactor -
protocol RecipeDetailInteractorProtocol: class {

  var presenter: RecipeDetailPresenterProtocol?  { get set }
}

//MARK: View -
protocol RecipeDetailViewProtocol: class {

  var presenter: RecipeDetailPresenterProtocol?  { get set }

  func didLoadDetail(from text: NSAttributedString)
  func didLoad(image: UIImage?)
}
